# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - pendulum_arm_controller

  pendulum_arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_joint
    action_ns: follow_joint_trajectory
    default: true